spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: sys as SYSDBA
    password: SYSTEM
    driver-class-name: oracle.jdbc.OracleDriver   
  jpa:
   properties:
    hibernate:
      dialect : org.hibernate.dialect.OracleDialect
      hbm2ddl-auto: update
    show-sql: true
server:
  port: 5003
  
  
