FROM openjdk:11
ADD target/SubscriberService-0.0.1-SNAPSHOT.jar SubscriberService-0.0.1-SNAPSHOT.jar

ADD src/main/resource/application.properties application.properties

ENTRYPOINT ["java","-jar","SubscriberService-0.0.1-SNAPSHOT.jar","-Dspring.config.location=application.properties"]