spring:
 application:
    name: SpringBootPostgresql
 datasource:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: anki$123
 jpa:
   hibernate:
     ddl-auto: update
     show-sql: true
 properties:
  hibernate:
    format_sql: true
    dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints: 
   web:
    exposure:
     include: 
server:
 port: 3000
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html  # Custom Swagger UI path
#  api-docs:
#    path: /api-docs 
# servlet:
#  context-path: /api/something
  