server:
  port: 1111

spring:
  profiles:
    active: dev
  cloud:
    config:
      uri: https://github.com/ankaiah504/bhumi-matrimony-properties.git
      server:
        git:
          uri: https://github.com/ankaiah504/bhumi-matrimony-properties.git
          search-paths:
            - 'ConfigData'
            - '{application}'
          clone-on-start: true  # 
          username: ankaiah.sree18@gmail.com  
          password: Shivanisree@143
          default-label: main
         
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
        
        
        
        
